// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFbIe6sW0KzAry_ljaHLneUsNi6e2Calk',
    appId: '1:653686733165:web:fd42268f79c4426cb0c264',
    messagingSenderId: '653686733165',
    projectId: 'announcement-app-69f95',
    authDomain: 'announcement-app-69f95.firebaseapp.com',
    storageBucket: 'announcement-app-69f95.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIGmUFpmU54loI8mbw559saAnJIjCtyQk',
    appId: '1:653686733165:android:301f3bda0b6375b4b0c264',
    messagingSenderId: '653686733165',
    projectId: 'announcement-app-69f95',
    storageBucket: 'announcement-app-69f95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWM9w-jK2IIiNgrgJz9ZDa8Z_ttF7mTuE',
    appId: '1:653686733165:ios:cbf2c20a35198e35b0c264',
    messagingSenderId: '653686733165',
    projectId: 'announcement-app-69f95',
    storageBucket: 'announcement-app-69f95.firebasestorage.app',
    iosBundleId: 'com.pixslide.announcementapp.announcementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWM9w-jK2IIiNgrgJz9ZDa8Z_ttF7mTuE',
    appId: '1:653686733165:ios:cbf2c20a35198e35b0c264',
    messagingSenderId: '653686733165',
    projectId: 'announcement-app-69f95',
    storageBucket: 'announcement-app-69f95.firebasestorage.app',
    iosBundleId: 'com.pixslide.announcementapp.announcementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFbIe6sW0KzAry_ljaHLneUsNi6e2Calk',
    appId: '1:653686733165:web:a317d8d521185045b0c264',
    messagingSenderId: '653686733165',
    projectId: 'announcement-app-69f95',
    authDomain: 'announcement-app-69f95.firebaseapp.com',
    storageBucket: 'announcement-app-69f95.firebasestorage.app',
  );
}
